name: echo action prod
on:
  workflow_dispatch:
  push:
    branches: [ env/prod ]
permissions:
  contents: read

jobs:
  echo-job-prod:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Run a script on prod
        run: |
          echo Hello, world!
