name: echo action main
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  echo-job-main:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Run a script
        run: |
          echo Hello, world!

  run-reusable-workflow:
    needs: echo-job-main
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my-message: "mike"
