name: echo action prod
on:
  workflow_dispatch:
  push:
    branches: [ env/prod ]
permissions:
  contents: read

jobs:
  echo-job-prod:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Run a script on prod
        run: |
          echo Hello, world!
