name: echo action
on:
  workflow_dispatch:
  push:
    branches: [ main, env/* ]
jobs:
  echo-job-main:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Run a script
        run: |
          echo Hello, world!
