name: echo action main
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  echo-job-main:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Run a script
        run: |
          echo Hello, world!

  run-reusable-workflow:
    needs: echo-job-main
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my-message: "mike"
