name: echo action prod
on:
  workflow_dispatch:
  push:
    branches: [ env/prod ]
jobs:
  echo-job-prod:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Run a script on prod
        run: |
          echo Hello, world!
