name: echo action main
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  echo-job-main:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Run a script
        run: |
          echo Hello, world!

  run-reusable-workflow:
    needs: echo-job-main
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my-message: "mike"
